Vagrant.configure("2") do |config|

  config.vm.define "web01" do |web01|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.box_version = "202309.08.0"
    web01.vm.hostname = "web01"

    web01.vm.network "private_network", ip: "192.168.56.11"
    web01.vm.network "public_network",  bridge: "enp2s0"

    web01.vm.provider "vmware_desktop" do |vd|
      vd.name   = "web01"
      vd.memory = "1024"
      vd.cpus   = 1
    end
  end

  config.vm.define "web02" do |web02|
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.box_version = "202309.08.0"
    web02.vm.hostname = "web02"

    web02.vm.network "private_network", ip: "192.168.56.12"
    web02.vm.network "public_network",  bridge: "enp2s0"

    web02.vm.provider "vmware_desktop" do |vd|
      vd.name   = "web02"
      vd.memory = "1024"
      vd.cpus   = 1
    end
  end

  config.vm.define "db01" do |db01|
    config.vm.box = "generic/centos9s"
    config.vm.box_version = "4.3.12"
    db01.vm.hostname = "db01"

    db01.vm.network "private_network", ip: "192.168.56.13"
    db01.vm.network "public_network",  bridge: "enp2s0"

    db01.vm.provider "vmware_desktop" do |vd|
      vd.name   = "db01"
      vd.memory = "1024"
      vd.cpus   = 1
    end

    db01.vm.provision "shell", inline: <<-SHELL
      yum install -y wget unzip mariadb-server
      systemctl start mariadb
      systemctl enable mariadb
    SHELL
  end

end