Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202309.08.0"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "public_network"
  config.vm.provider "vmware_desktop" do |vd|
    vd.memory = "1024"
    vd.cpus = 2
  end
  #

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y \
      apache2 \
      ghostscript \
      libapache2-mod-php \
      mysql-server \
      php \
      php-bcmath \
      php-curl \
      php-imagick \
      php-intl \
      php-json \
      php-mbstring \
      php-mysql \
      php-xml \
      php-zip
  
    mkdir -p /srv/www
    chown www-data: /srv/www
    curl https://wordpress.org/latest.tar.gz | sudo -u www-data tar zx -C /srv/www
  
    cat > /etc/apache2/sites-available/wordpress.conf <<EOF
<VirtualHost *:80>
  DocumentRoot /srv/www/wordpress
  <Directory /srv/www/wordpress>
      Options FollowSymLinks
      AllowOverride Limit Options FileInfo
      DirectoryIndex index.php
      Require all granted
  </Directory>
  <Directory /srv/www/wordpress/wp-content>
      Options FollowSymLinks
      Require all granted
  </Directory>
</VirtualHost>
EOF
  
    a2ensite wordpress
    a2enmod rewrite
    a2dissite 000-default
    service apache2 reload
  
    service mysql start
    mysql -u root -e 'CREATE DATABASE wordpress;'
    mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "admin123";'
    mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'
    mysql -u root -e 'FLUSH PRIVILEGES;'
  
    sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
    sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
    sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
    sudo -u www-data sed -i 's/password_here/admin123/' /srv/www/wordpress/wp-config.php
  
    systemctl restart apache2
  SHELL
end
