Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos9s"
  config.vm.box_version = "4.3.12"
  config.vm.network "private_network", ip: "192.168.57.20"
  config.vm.network "public_network", bridge: "enp2s0"
  config.vm.provider "vmware_desktop" do |vd|
    vd.linked_clone = false
    vd.memory = "1024"
    vd.cpus = 2
  end

  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    dnf update
    dnf upgrade -y
    dnf install httpd -y
    
    wget https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.55/bin/apache-tomcat-10.1.55.tar.gz
    tar xzvf apache-tomcat-10.1.55.tar.gz
    sudo cp -r apache-tomcat-10.1.55/* /opt/tomcat/
    sudo chown -R tomcat:tomcat /opt/tomcat/
    dnf install java-17-openjdk -y
  
    sudo firewall-cmd --permanent --add-service=http
    sudo firewall-cmd --permanent --add-service=https
    sudo firewall-cmd --permanent --add-port=8080/tcp
    sudo firewall-cmd --reload

    sudo apache-tomcat-10.1.55/bin/startup.sh
    sudo useradd --home-dir /opt/tomcat --shell /sbin/nologin tomcat
    sudo tee /etc/systemd/system/tomcat.service <<EOF
[Unit]
Description=Apache Tomcat 10
After=network.target

[Service]
Type=forking

User=tomcat
Group=tomcat

WorkingDirectory=/opt/tomcat

Environment=JAVA_HOME=/usr/lib/jvm/jre
Environment=CATALINA_HOME=/opt/tomcat
Environment=CATALINA_BASE=/opt/tomcat

ExecStart=/opt/tomcat/bin/startup.sh
ExecStop=/opt/tomcat/bin/shutdown.sh

[Install]
WantedBy=multi-user.target
EOF
    sudo systemctl enable httpd
    sudo systemctl start httpd
  SHELL
end
