Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"

    # Private network with static IP
    config.vm.network "private_network", ip: "192.168.56.17"

    # Public network (bridged), no static IP
    config.vm.network "public_network", bridge: "enp2s0"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
    end
end    